name: Generate Amlogic Firmware

on:
  workflow_dispatch:
    inputs:
      release_branch:
        description: "Select the release branch:"
        required: true
        default: "openwrt:24.10.0"
        type: choice
        options:
          - openwrt:24.10.0
          - openwrt:23.05.5
          - immortalwrt:24.10.0
          - immortalwrt:23.05.4
      target:
        description: "Select device board"
        required: true
        default: "s905x"
        type: choice
        options:
          - all
          - s905x
          - s905x-b860h
          - s905x_s905x-b860h
      openwrt_kernel:
        description: "Select kernel version"
        required: false
        default: "5.15.y_6.6.y"
        type: choice
        options:
          - 5.4.y
          - 5.10.y
          - 5.15.y
          - 6.1.y
          - 6.6.y
          - 6.1.y_6.6.y
          - 5.15.y_6.6.y
      tunnel:
        description: "Select VPN Client app:"
        required: true
        default: "openclash"
        type: choice
        options:
          - all
          - openclash
          - passwall
          - nikki
          - openclash-passwall
          - nikki-passwall
          - nikki-openclash
          - openclash-passwall-nikki
          - no-tunnel
      clean:
        description: "Do 'make clean' for each run"
        required: false
        default: "true"
        type: boolean

env:
  TYPE: AMLOGIC
  TARGET: ${{ inputs.target }}
  RELEASE_BRANCH: ${{ inputs.release_branch }}
  TUNNEL: ${{ inputs.tunnel }}
  CLEAN: ${{ inputs.clean }}
  TZ: Asia/Jakarta
  WORKING_DIR: imagebuilder
  DEBIAN_FRONTEND: noninteractive

jobs:
  Generate:
    runs-on: ubuntu-latest

    steps:
      - name: Check System Requirements
        run: |
          echo "Checking system requirements..."
          echo "CPU Architecture: $(uname -m)"
          echo "Available RAM: $(free -h)"
          echo "Available Disk Space: $(df -h /)"
          echo "Selected tunnel option: [${{ env.TUNNEL }}]"
          echo "status=success" >> $GITHUB_OUTPUT

  build-firmware:
    name: Build ${{ inputs.target }}-${{ inputs.release_branch }}-${{ inputs.tunnel }}
    runs-on: ubuntu-latest

    steps:
      - name: Initialization environment
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git gettext libssl-dev xsltproc rsync wget unzip qemu-utils mkisofs
          
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          path: origin

      - name: Setup Build Variables
        id: variables
        run: |
          # Set board variable
          case "${{ env.TARGET }}" in
            "all")
              echo "openwrt_board=all" >> $GITHUB_ENV
              ;;
            "hg680p"|"b860h")
              echo "openwrt_board=s905x" >> $GITHUB_ENV
              ;;
            "nanopi-r5s")
              echo "openwrt_board=rk3568" >> $GITHUB_ENV
              ;;
            *)
              echo "openwrt_board=${{ env.TARGET }}" >> $GITHUB_ENV
              ;;
          esac

          # Set architecture variables
          echo "PROFILE=generic" >> $GITHUB_ENV
          echo "TARGET_SYSTEM=armsr/armv8" >> $GITHUB_ENV
          echo "TARGET_NAME=armsr-armv8" >> $GITHUB_ENV
          echo "ARCH_1=arm64" >> $GITHUB_ENV
          echo "ARCH_2=aarch64" >> $GITHUB_ENV
          echo "ARCH_3=aarch64_generic" >> $GITHUB_ENV

          # Set base distribution info
          BASE="${RELEASE_BRANCH%:*}"
          BRANCH="${RELEASE_BRANCH#*:}"
          VEROP="$(echo "${BRANCH}" | awk -F. '{print $1"."$2}')"

          echo "BASE=$BASE" >> $GITHUB_ENV
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV
          echo "VEROP=$VEROP" >> $GITHUB_ENV
          echo "DOWNLOAD_BASE=https://downloads.${BASE}.org" >> $GITHUB_ENV

          # Set date variables
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
          echo "DATETIME=$(date +'%Y.%m.%d-%H:%M:%S')" >> $GITHUB_ENV
          echo "DATEMONTH=$(date +"%B-%Y" | awk '{print tolower($0)}')" >> $GITHUB_ENV

          echo "Build variables configured successfully"
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Download and Prepare Image Builder
        id: download
        if: steps.variables.outputs.status == 'success'
        run: |
          # Determine archive extension
          CURVER=$(echo "${{ env.BRANCH }}" | cut -d'.' -f1)
          archive_ext=$([ "${CURVER}" == "24" ] && echo "tar.zst" || echo "tar.xz")

          # Download image builder
          RELEASE="${{ env.DOWNLOAD_BASE }}/releases/${{ env.BRANCH }}/targets/${{ env.TARGET_SYSTEM }}/${{ env.BASE }}-imagebuilder-${{ env.BRANCH }}-${{ env.TARGET_NAME }}.Linux-x86_64.${archive_ext}"
          echo "Downloading from: $RELEASE"
          wget --progress=dot:giga "$RELEASE"

          # Extract archive
          case "${archive_ext}" in
            tar.xz)
              tar -xJf *-imagebuilder-* && rm -f *-imagebuilder-*.tar.xz
              ;;
            tar.zst)
              tar --use-compress-program=unzstd -xf *-imagebuilder-* && rm -f *-imagebuilder-*.tar.zst
              ;;
          esac

          # Setup working directory
          mv *-imagebuilder-* ${{ env.WORKING_DIR }}
          cp -r $GITHUB_WORKSPACE/origin/* $GITHUB_WORKSPACE/${{ env.WORKING_DIR }}

          echo "Image builder prepared successfully"
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Download External Packages
        id: packages
        if: steps.download.outputs.status == 'success'
        run: |
          cd ${{ env.WORKING_DIR }}
          chmod +x scripts/PACKAGES.sh
          ./scripts/PACKAGES.sh

          PACKAGE_COUNT=$(find packages -type f -name "*.ipk" | wc -l)
          echo "Downloaded $PACKAGE_COUNT external packages"
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Apply Patches and Customizations
        id: customize
        if: steps.packages.outputs.status == 'success'
        run: |
          cd ${{ env.WORKING_DIR }}

          # Apply patches
          chmod +x scripts/PATCH.sh
          ./scripts/PATCH.sh

          # Apply miscellaneous changes
          chmod +x scripts/MISC.sh
          ./scripts/MISC.sh

          # Configure tunnel apps
          chmod +x scripts/TUNNEL.sh
          if [[ "${{ env.TUNNEL }}" == "all" ]]; then
            ./scripts/TUNNEL.sh openclash-passwall-nikki
          elif [[ "${{ env.TUNNEL }}" =~ ^(openclash|passwall|nikki|openclash-passwall|nikki-passwall|nikki-openclash|openclash-passwall-nikki)$ ]]; then
            ./scripts/TUNNEL.sh "${{ env.TUNNEL }}"
          fi

          echo "Customizations applied successfully"
          df -hT ${PWD}
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Build Firmware Images
        id: build
        if: steps.customize.outputs.status == 'success'
        run: |
          cd ${{ env.WORKING_DIR }}
          mkdir -p compiled_images
          chmod +x make-image.sh

          build_image() {
            local tunnel=$1
            echo "Building with VPN Client: $tunnel"
            
            # Clean if requested
            if [ "${{ env.CLEAN }}" == "true" ]; then
              make clean
            fi
            
            # Build image
            time ./make-image.sh ${{ env.PROFILE }} $tunnel
            
            # Move and rename output files
            for file in bin/targets/"${{ env.TARGET_SYSTEM }}"/*rootfs.tar.gz; do
              if [ -f "$file" ]; then
                new_name="RTA-WRT_$(basename "$file" .tar.gz)_${tunnel}.tar.gz"
                mv "$file" compiled_images/$new_name
              fi
            done
          }

          if [[ "${{ env.TUNNEL }}" == "all" ]]; then
            for tunnel in openclash passwall nikki openclash-passwall nikki-passwall nikki-openclash openclash-passwall-nikki no-tunnel; do
              build_image $tunnel
            done
          else
            build_image ${{ env.TUNNEL }}
          fi

          echo "Images built successfully:"
          ls -la compiled_images/
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Package Amlogic Images
        id: package
        if: steps.build.outputs.status == 'success'
        run: |
          cd ${{ env.WORKING_DIR }}

          package_image() {
            local tunnel=$1
            echo "Packaging images for: $tunnel"
            
            git clone --depth 1 https://github.com/ophub/amlogic-s9xxx-openwrt.git
            mkdir -p amlogic-s9xxx-openwrt/openwrt-armvirt
            
            for file in compiled_images/*_${tunnel}.tar.gz; do
              if [ -f "$file" ]; then
                mv "$file" amlogic-s9xxx-openwrt/openwrt-armvirt/RTA-WRT_openwrt-armsr-armv8-generic-rootfs.tar.gz
                cd amlogic-s9xxx-openwrt
                sudo ./remake -b ${{ env.openwrt_board }} -k ${{ inputs.openwrt_kernel }} -s 1024
                
                cd ${{ env.PACKAGED_OUTPUTPATH }}
                for img in *.img.gz; do
                  new_name="RTA-WRT_$(basename "$img" .img.gz)_${tunnel}.img.gz"
                  mv "$img" "$GITHUB_WORKSPACE/${{ env.WORKING_DIR }}/compiled_images/$new_name"
                done
                cd $GITHUB_WORKSPACE/${{ env.WORKING_DIR }}
              fi
            done
            
            sudo rm -rf amlogic-s9xxx-openwrt
          }

          if [[ "${{ env.TUNNEL }}" == "all" ]]; then
            for tunnel in openclash passwall nikki openclash-passwall nikki-passwall nikki-openclash openclash-passwall-nikki no-tunnel; do
              package_image $tunnel
            done
          else
            package_image ${{ env.TUNNEL }}
          fi

          echo "Images packaged successfully"
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Mod SDCard
        id: modsdcard
        if: steps.package.outputs.status == 'success'
        run: |
          cd ${{ env.WORKING_DIR }}

          chmod +x scripts/MODSDCARD.sh
          ./scripts/MODSDCARD.sh
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Create Release
        if: steps.modsdcard.outputs.status == 'success'
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: amlogic
          name: RTA-WRT-Amlogic-${{ env.BRANCH }}-${{ env.TUNNEL }}-${{ env.DATE }}
          files: ${{ env.WORKING_DIR }}/compiled_images/*.gz
          prerelease: true
          generate_release_notes: true
